{% set version = "1.5.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-bigrquery
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bigrquery_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bigrquery/bigrquery_{{ version }}.tar.gz
  sha256: ca56da71f1028a642c9255685b6946956f6c25c160a06d59c0530fa4664f7572

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dbi
    - r-bit64
    - r-brio
    - r-cli
    - r-clock
    - r-cpp11
    - r-curl
    - r-gargle >=1.5.0
    - r-httr
    - r-jsonlite
    - r-lifecycle
    - r-prettyunits
    - r-rapidjsonr
    - r-rlang >=1.1.0
    - r-tibble
  run:
    - r-base
    - r-dbi
    - r-bit64
    - r-brio
    - r-cli
    - r-clock
    - r-cpp11
    - r-curl
    - r-gargle >=1.5.0
    - r-httr
    - r-jsonlite
    - r-lifecycle
    - r-prettyunits
    - r-rapidjsonr
    - r-rlang >=1.1.0
    - r-tibble

test:
  commands:
    - $R -e "library('bigrquery')"           # [not win]
    - "\"%R%\" -e \"library('bigrquery')\""  # [win]

about:
  home: https://bigrquery.r-dbi.org/
  dev_url: https://github.com/r-dbi/bigrquery
  license: MIT
  summary: Easily talk to Google's 'BigQuery' database from R.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - adrianzo
