appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: mGAXlB9w6mYzXa4A0c2yFKlQmXZWlo1lMwHoVIiXykWttdz2aCLDNljX10+rXTEQIodw/B3LhWasvwfn593cLljF1aKstd6IkozRSSK6m+KAVwprrh6DuqqQ25KXSSLHs7QbzDc5q26lK42HgDioKxrQjL1XaTB4p28EmiwdcyaQhWnh9QsU1btTnNpzEYB+Iiy3d8bcG9dZ+LZOT3D8w/4WFKvUattHrvYGQW2IWcRM/N0PJixbOmwyE2Iw4tyIveuj0TkDXkeKObxC53NuLdARcUdg33SaTIW78+3Y7TEntMc63E66zn4I9KCuV+TuggRn/lfPyi91gJyZXVd99eSdDiZ+RkrC+3NAU8Yc9Q2Gh0EwkhJeZxBTzGrkPULRvNUqkayRHwmbh9NrrlCjU1E64hfPMg6pYS/W5+VR/qWmi8oxQ4H/wnLNsRKwoxhuOdGEvw8szX4Ky6SpcNQf4QYeX0RjXWSsWPmnSfsldKJ8zB7WFI2qY+DUd2uxV2zbaj0NtJrVTxYnuiHT6/D/Q4E9T+MJuADu1jOe7axy8fPBVaoIpZViXrOLqa5IRaenlgMtMwA7bOs+hcUsvdUTNVRQvQmLkm9+8vwohOckSPIcPIo7y6XWrbgx0fkwLPP5HkgHa0zTg7MrSvgHjoXoXKzUXiEg1PclxVcgot5excg=
